### ISSUE TITLE
SDF parser not generating correct results for RDKit-generated files

### ISSUE THREAD

**Issue by iainmaryanow** [molstar/molstar#151] opened 2021-03-22 12:35 UTC
Hi,

I am working with an SDF file in Molstar and ran into an issue when parsing with `mol-io/reader/sdf/parser.ts`. The `parseInternal` function is using the delimiter of `$$$$` which is correct but the tokenizer is then not considering the next character of `\n` as valid, so any molecules in the SDF are not correctly generated.

This happens in the case of RDKit-generated SDF files which are delimited with the new line between the delimiter and the molecule title like the following snippet:

```
...
M  CHG  3   1   1   4  -1  32  -1
M  END
>  <_TriposChargeType>  (1) 
GAST_HUCK

> <PKD>
-0.40

$$$$
ligand_2
     RDKit          3D

 59 60  0  0  0  0  0  0  0  0999 V2000
   15.0880   10.7980   23.5470 N   0  0  0  0  0  4  0  0  0  0  0  0
   15.0100    9.9870   24.7920 C   0  0  2  0  0  0  0  0  0  0  0  0
...
```

Right now `parseSdf` will create a result with two compounds but the second will not have the expected data.

It seems that trimming the data before the Tokenizer would work but I want to make sure that's the correct solution.

To clarify, the following is currently necessary to properly be parsed:
```
...
> <PKD>
-0.40

$$$$ligand_2
     RDKit          3D
...
```

**Comment by dsehnal** [comment] 2021-03-22 15:16
Thanks for the report, I will look into fixing it this week.

**Comment by dsehnal** [comment] 2021-03-22 17:47
It should be fixed in 5df55e6. NPM package coming soon.

**Comment by iainmaryanow** [comment] 2021-03-23 12:27
Awesome, thanks for the quick reply

**Comment by iainmaryanow** [comment] 2021-03-24 11:36
Hey David,

Looks like there is now a bug in the SDF parser after the changes. The compounds are parsed correctly (now without me having to specify 'sdf' as a customFormat), however, there is an issue when the `dataItems` are created.

I have an SDF with two molecules, after `parseSdf`, I can see the `molFile` for each has the correct data for the atoms and bonds (I confirmed by looking at the values for different rows in the atoms `x`, `y`, and `z`). But when I do `sdf.result.compounds[0].dataItems.data.value()`, I get the same data string as for the other molecule`sdf.result.compounds[1].dataItems.data.value()`.

It seems that now since the same tokenizer is being used for all molecules in the SDF, it is only using the first when creating the dataItems value.

**Comment by dsehnal** [comment] 2021-03-24 15:04
I just wrote this test https://github.com/molstar/molstar/commit/861e5c3e9747123578cc9fa3c422bb309d1171ca and it seems to work as expected. Can you send me your data and code so I can investigate further?

**Comment by dsehnal** [comment] 2021-03-24 15:54
I think the issue is that you are calling ``value()`` instead of ``value(0)``. We "force" the user to call the function with an argument. The reason for this is that if you call the same function with different number of args, in will cause a de-optimization in the JS runtime.

**Comment by iainmaryanow** [comment] 2021-03-24 16:36
I guess I misunderstood the method then because before the 2.0.1 release, the `compounds` would return the entire data string that was used to create the molFile. Meaning that when I called `compound.dataItems.data.value()`, it would return the part of the data string for the SDF that was used to generate the compound.

However, as I write this, I assume I was working off of the buggy behavior before your changes. Leading to my next question of how can I either recreate the data string used for each compound or if there is a way to create a Model from a `MolFile`.

I am looking to create individual models and structures for each compound within the SDF instead of a trajectory with multiple frames.

**Comment by dsehnal** [comment] 2021-03-24 17:03
> I guess I misunderstood the method then because before the 2.0.1 release, the `compounds` would return the entire data string that was used to create the molFile. Meaning that when I called `compound.dataItems.data.value()`, it would return the part of the data string for the SDF that was used to generate the compound.
> 
> However, as I write this, I assume I was working off of the buggy behavior before your changes. Leading to my next question of how can I either recreate the data string used for each compound or if there is a way to create a Model from a `MolFile`.

You indeed did rely on some "undefined behavior".

> 
> I am looking to create individual models and structures for each compound within the SDF instead of a trajectory with multiple frames.

Before you create a Model, you usually need to have trajectory anyway. You can "project" the trajectory to multiple models at the same time too. If you tell me more about what what your goals are, perhaps I can help you with the implementation.

**Comment by iainmaryanow** [comment] 2021-03-24 17:59
My goal is to have individual representations for each of the compounds in the SDF file instead of a single trajectory with frames that can be stepped through (as the compounds in this file are just a list of ligands to be shown at the same time).

Right now, each frame, as I understand it, in the returned trajectory is a model itself. I'm not sure what you mean "project" but maybe this description helps.

**Comment by dsehnal** [comment] 2021-03-24 18:46
This will do trick:

```
const data = ...;
const trajectory = await this.plugin.builders.structure.parseTrajectory(data, 'sdf');
for (let i = 0; i < trajectory.data!.frameCount; i++) {
  const model = await this.plugin.builders.structure.createModel(trajectory);
  // create representation here
}
```

**Comment by iainmaryanow** [comment] 2021-03-25 10:42
Ah yes, that is exactly what I was trying to do, I just didn't know about the `modelIndex` parameter.

Thank you again

**Comment by dsehnal** [comment] 2021-03-25 10:54
Tip: In VS Code you should get the type definitions. Pressing "Go to definition" should help to easily navigate to available options for the functions.

**Closed** 2021-05-10 03:16 UTC
Labels: bug, question
