### ISSUE TITLE
Viewer freezes when trying to change a third parameter in ColorTheme/Palett/GenerateDistinct

### ISSUE THREAD

**Issue by Henklem** [molstar/molstar#852] opened 2023-07-06 09:50 UTC
I wanted to apply a custom color to the surface of PDB structure 7p4x. Changing two values from among Hue, Chroma and Luminance works fine but when trying to change the third one (or after changing the second) the tool freezes.

**Comment by dsehnal** [comment] 2023-07-07 06:04
I tried playing with these settings 

![image](https://github.com/molstar/molstar/assets/21145776/6f5f11a1-f436-4b91-b88f-0296d90acf3e)

And was unable to reproduce your issue.

**Comment by midlik** [comment] 2023-07-07 11:24
Hi, the problem occurs when you set any of the ranges to a zero-length interval, e.g. Chroma 100-100.

<img width="296" alt="Screenshot 2023-07-07 at 12 17 42" src="https://github.com/molstar/molstar/assets/14818844/7b42b27e-8b4f-4fd8-8f76-c535329487c9">

The culprit is in this loop I think:
https://github.com/molstar/molstar/blob/5e1c351efca88365ccaa8c76746f0a6389abf070/src/mol-util/color/distinct.ts#L87
When any of the steps is 0, it will loop forever.

**Comment by dsehnal** [comment] 2023-07-07 15:13
Thanks for the pointer, should be fixed by https://github.com/molstar/molstar/pull/857

**Comment by midlik** [comment] 2023-07-07 18:44
Nice, but now when there are too many chains, not enough samples will be generated and everything will be grey. 
In fact, it can happen even without setting a zero-length interval, in the current Mol* version :(

<img width="1046" alt="Screenshot 2023-07-07 at 19 39 13" src="https://github.com/molstar/molstar/assets/14818844/e22e88ac-02a5-4d32-90dc-c68e41c9815c">

(ignore if this behavior is intentional)

**Comment by arose** [comment] 2023-07-08 19:27
It is a tradeoff, when you increase the maxCount it should occur less (at a performance cost). Please feel free to investigate this and make suggestions to improve!

**Closed** 2023-07-11 06:52 UTC
