### ISSUE TITLE
Selecting atoms in a line represenation (e.g. for distance measurement)

### ISSUE THREAD

**Issue by prakashrathi** [molstar/molstar#267] opened 2021-09-14 10:51 UTC
First of all thanks for creating a wonderful 3D viewer. Atom selection in UI works flwless for ball and stick representation, but it is is impossible to select atoms in a line represention. Even when I precisely click on an atom location, the UI tends to select a bond. Is this by design and if so what is the best workaround for selecting atoms in line representation, e.g. for distance measurement?

**Comment by dsehnal** [comment] 2021-09-14 12:08
This is currently by design/implementation shortcut.
I would suggest adding sphere-only ball and stick visual with small size factor:

![image](https://user-images.githubusercontent.com/21145776/133253989-daca6651-c350-4661-8702-649456c1a35f.png)

Could also add some transparency. But for this to work for alpha < 0.5, the ``pickingAlphaThreshold`` of the canvas renderer needs to be adjusted.

I also tried ``0.001`` opacity to make the spheres invisible, but there is currently a [hard-coded limit of 0.1 opacity](https://github.com/molstar/molstar/blob/master/src/mol-gl/shader/chunks/check-picking-alpha.glsl.ts#L5) for an element to be pickable (tho this is fixable, so let us know if the small sphere solution does not work for you).

**Comment by prakashrathi** [comment] 2021-09-14 12:17
Thank you very much for the quick response and proposing a workabale solution. This is what I was hoping to do (programatically creating a ball and stick with thin sticks - thanks for pointing to "sphere-only ball and stick"). This will work for us and we would like to make the spheres invisible so a fix for changing/removing opacity cutoff for picking will be very much appreciated. We will try the solution and get back.

**Comment by arose** [comment] 2021-09-15 06:04
I think we can support that directly without resorting to adding extra invisible spheres. There are two aspects to this
1. selecting atoms when clicking near one of the ends of a bond
2. having a large enough area around any pickable object

For 1) I propose we add a global option `preferAtomOverBondDistance`. If the reconstructed 3D position of the mouse cursor is closer than that distance to an atom in the bond, the atom gets picked instead of the bond.

For 2) I don't think this is too much of a problem. The picking buffer is rendered a quarter resolution so there are always a few more pixels pickable than what you see on screen.

To add to @dsehnal's suggestion, there is also a point representation which (with size attenuation turned off) you can use instead of Ball&Stick (instead of Ball&Stick you can also use Spacefill with a small size factor).

**Comment by prakashrathi** [comment] 2021-09-15 09:06
Thanks @arose, A native solution without invisible shperes will be a great addition to Mol* as this is one of the common use case to measure distances between protein (usually rendered as lines) and ligands. If you can indicate a rough timeline when this can be implemented, we can decide whether to wait for the feature or create a workaround for now.

**Comment by arose** [comment] 2021-09-19 23:35
Hi @prakashrathi, please give #267 a try and feel free to tweak it/work on the todos there.

Would you be interested in implementing some of the missing line representation related features that exist in NGL? From the top of my head there multipleBonds (off, symmetric, offset) and the crosses settings.

**Comment by prakashrathi** [comment] 2021-09-21 17:48
Thanks. We will try and get back. On the question of contributing missing line representation features, I will have to get back after discussing within the team.

**Comment by arose** [comment] 2021-10-03 18:20
Hi, quick update. The picking improvements (#271) is merged. I also took the liberty to add the off/symmetric/offset multipleBonds options (dcaf6f892717f5f225cbe760a9d93093abaa5423) and a crosses visual (d96eb404e1becc62d4e8f2caa9d6ae9918b717a0).

**Closed** 2021-12-30 01:54 UTC
Labels: enhancement, question
