### ISSUE TITLE
Problem that occurs when you go back to the browser in the toggle menu expand window

### ISSUE THREAD

**Issue by arontier-yskim** [molstar/molstar#596] opened 2022-10-21 02:09 UTC
When the expanded window is toggled, the body style is normally initialized, but when you go back to the browser, the body style is not initialized and overflow remains in the none state.

I think the unmounted event should be implemented additionally.

**Comment by dsehnal** [comment] 2022-10-21 11:32
So the issue is that you create a new instance of a plugin in expanded state (which modifies the body style), then you remove it without un-expanding it and the body style stays modified?

This seems to be a very rare use-case of the plugin. I think could be fixed by calling `PluginCommands.Layout.Update(this.plugin, { state: { isExpanded: false } });` before you remove the plugin.

**Closed** 2023-02-11 19:26 UTC
Labels: enhancement, question
