### ISSUE TITLE
Question about representation visuals

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#635] opened 2022-11-25 11:20 UTC
I'm trying to modify a representation visual to learn how it works. I have a few questions:
- Can I make a visual where some specific parts of its mesh can have a variable opacity? Or should I make two separate visuals to achieve this?
- Can i make a visual composed of mesh and impostors at the same time?
- How to construct a visual in order to be able to distinguish specific parts of it in the color theme?

**Comment by arose** [comment] 2022-11-25 21:05
> Can I make a visual where some specific parts of its mesh can have a variable opacity? Or should I make two separate visuals to achieve this?

You can use `Representation.setState({ transparency })` for per-group transparency.

> Can i make a visual composed of mesh and impostors at the same time?

No, you should create a representation with two visuals.

> How to construct a visual in order to be able to distinguish specific parts of it in the color theme?

When creating geometry (mesh, spheres, lines, ...) you assign a `group` to a vertex, sphere, line, ... When creating a visual you provide functions that map those groups to locations and loci.

Have a look at https://github.com/molstar/molstar/blob/0b2459f4e1f87d95b189aca851883f3bc2024e66/src/mol-repr/structure/visual/carbohydrate-symbol-mesh.ts for an example that does not use structure element index as the `group`.

**Comment by giagitom** [comment] 2022-11-28 17:22
Thanks @arose.

> When creating geometry (mesh, spheres, lines, ...) you assign a group to a vertex, sphere, line, ... When creating a visual you provide functions that map those groups to locations and **loci.**

so basically `builderState.currentGroup` is used to set the correct group for the next mesh to be added?

**Comment by arose** [comment] 2022-11-28 18:33
> so basically builderState.currentGroup is used to set the correct group for the next mesh to be added?

for meshes, yes

**Comment by giagitom** [comment] 2022-12-03 16:08
I'm searching for a way to alter the opacity of a specific visual without altering opacity of all other visuals in the representation. Is it possible in some way?

**Comment by arose** [comment] 2022-12-03 20:23
Not really, only via setTransparency and only if the visuals map to different loci. Probably best to create multiple representations.

**Comment by giagitom** [comment] 2022-12-04 16:00
Ok thanks, I'll work with two representations and show the second only when necessary. By the way, which is the correct way to hide/show a representation? Should I add/remove it from the canvas using ```canvas3d.remove(repr)``` or ```canvas3d.add(repr)```? Or there is a better way?

**Comment by arose** [comment] 2022-12-04 17:46
Use `repr.setState({ visible: false });`. Just improved the typing a bit in f84b5b633d36f32a0bc4c527dc743506a02e92b5.

**Comment by giagitom** [comment] 2022-12-05 18:50
A few other questions about this
- I also noticed this artifacts on sphere-cylinder intersection. Is this due to a different size between sphere and cylinder visuals? 
- How to change the size of an impostor sphere ? I was able to change the size of impostor cylinders using ```builder.add``` but not for spheres.  

![image](https://user-images.githubusercontent.com/20627977/205714662-56752aca-9c14-4030-b19a-175e9120a9d9.png)

**Comment by giagitom** [comment] 2022-12-06 19:47
> Looks fine for me. Can you share a state to reproduce?

The problem is that I'm experiencing this issue only with my custom visuals. I suspect there is something wrong on my side. Have you ever experienced something like this? The artifact shows on the edges of the impostor cylinder

![image](https://user-images.githubusercontent.com/20627977/206007388-614b0d1f-8e70-4cf7-bf21-5d57e7e03c9e.png)
![image](https://user-images.githubusercontent.com/20627977/206007582-35607969-f358-4afe-b12a-8d51a393be11.png)

**Comment by arose** [comment] 2022-12-07 06:51
Came across the issue elsewhere :) It is caused by a bug with bumpiness in impostors. Don't know how to fix the actual bug (may just be a side-effect of using derivatives) but can guard against it better in 65310e52de41ed90b66a5ac85c6a18887f8fee4e.

**Comment by giagitom** [comment] 2022-12-07 13:21
Awesome thanks! It solved the problem :)

Regarding impostors i have found something else with ```interiorColorFlag``` on

- seems that impostor spheres lose interiors for big structures? Is this possible? Because using spacefill on entry 4V6X I can't see interior when clipping using the camera zoom

![image](https://user-images.githubusercontent.com/20627977/206168940-1d8593cd-ad1e-4c1c-89d3-57577c3c8a5e.png)

- Furthermore impostor cylinders interior mode seems to be broken when clipping with camera zoom
![image](https://user-images.githubusercontent.com/20627977/206189884-9cc38973-6138-4b03-a5f6-7fb9a3970c8d.png)

**Comment by giagitom** [comment] 2022-12-08 23:19
Thanks! It it worked for spheres

**Comment by arose** [comment] 2022-12-11 05:48
Hey @giagitom, I fixed a few issues with impostor shaders in 601bd5ba7a634eb5fd6f28a28b4337e450a0f710. Could you please test it?

**Comment by giagitom** [comment] 2022-12-11 17:23
Hey @arose , I tested it and I think it is working very well, thank you! 

One thing I noticed is attached below. When clip occurs, depending on the orientation, it could happen that some exterior parts of the sphere (in this case, but also any other impostor / mesh) are shown too. 

I was thinking that one way to draw only interiors would be to set ```gl_FragDepthEXT = (0.0 or clipDepth?)``` when interior is detected. It would be necessary also a way to know if the impostor is in the clipping range and set ```gl_FragDepthEXT``` only in that case. Do you think this could be possible? Or maybe you have a better solution in mind?

![image](https://user-images.githubusercontent.com/20627977/206915636-fdcb58b5-da78-4c9c-8644-8642ab40588c.png)

**Comment by arose** [comment] 2022-12-12 04:58
We do that for spheres for near-clipping (the radius bias is to favor larger spheres over smaller ones)

```
    if (interior) {
        fragmentDepth = 0.0 + (0.0000001 / vRadius);
    }
```

but it is not generally possible without doing an extra pass that can tell us if a interior fragment will be visible after all fragment are rendered. For example a interior fragment can be drawn before a non-interior fragment that will cover the interior fragment and if we change the interior fragment's depth to the clip depth the non-interior fragment will not cover it anymore. To avoid that you could do a depth pre-pass (or instead of depth just flag for interior or not) and use that in the actual draw pass to decide weather or not to set the fragment depth to the clip/near depth. I haven't tried this but I think it can work and would be nice even with the extra pass. Handling transparency would also require some thinking.

**Comment by giagitom** [comment] 2022-12-12 17:03
For the special case in which topCap and bottomCap are both present, interior parts should be visible only when clipping happens, so we could treat it like in the sphere case. Want a PR for this?

**Comment by giagitom** [comment] 2022-12-12 18:19
I also noticed this when clipping an isolated cylinder with both caps on. In the opposite sense it works fine instead. Maybe is something related to bottomCap but not entirely sure. Top cap seems to work fine instead.

- problem
![image](https://user-images.githubusercontent.com/20627977/207114259-2892637f-eee1-42c3-8f29-20edb2863fed.png)

- correct 
![image](https://user-images.githubusercontent.com/20627977/207115518-0751bf91-cd9e-42ba-8d6b-4ae50d86a522.png)

**Comment by arose** [comment] 2022-12-13 06:01
> I also noticed this when clipping an isolated cylinder with both caps on. In the opposite sense it works fine instead. Maybe is something related to bottomCap but not entirely sure. Top cap seems to work fine instead.

fixed with 4ff5ed3b5d5b2e736181bd1c467b259d9634066c, issue was with the cylinder direction

**Comment by arose** [comment] 2022-12-13 06:02
> For the special case in which topCap and bottomCap are both present, interior parts should be visible only when clipping happens, so we could treat it like in the sphere case. Want a PR for this?

I am not sure it is possible, if you can make it work, great :)

**Comment by arose** [comment] 2022-12-13 06:03
> I haven't tried this but I think it can work and would be nice even with the extra pass. Handling transparency would also require some thinking.

Thinking about it some more, this will not work :(

**Comment by giagitom** [comment] 2022-12-13 14:39
> fixed with https://github.com/molstar/molstar/commit/4ff5ed3b5d5b2e736181bd1c467b259d9634066c, issue was with the cylinder direction

awesome!


> I am not sure it is possible, if you can make it work, great :)

On default ball and sticks repr there is no way to enable both caps. But it seems to work very well on my custom visual :)

**Comment by giagitom** [comment] 2022-12-13 14:48
I just noticed some artifacts on overlaps (maybe z-fighting issue?)

![image](https://user-images.githubusercontent.com/20627977/207365024-83b9525c-4124-4a23-acb5-63c651325584.png)

**Comment by giagitom** [comment] 2022-12-20 11:04
>Use a size-theme (works same as color-theme). See createElementSphereImpostor and createElementSphereMesh in src\mol-repr\structure\visual\util\element.ts

@arose in my custom representation that contains meshes and impostor cylinders and spheres I would like to set an aspectRatio parameter to vary the impostors size respect to the meshes.. is it possible to achieve this using a size theme?

**Comment by arose** [comment] 2023-02-11 19:22
> @arose in my custom representation that contains meshes and impostor cylinders and spheres I would like to set an aspectRatio parameter to vary the impostors size respect to the meshes.. is it possible to achieve this using a size theme?

Probably best to have scaleCylinder, scaleSphere, scaleMesh... params

**Comment by giagitom** [comment] 2023-02-14 21:35
> Probably best to have scaleCylinder, scaleSphere, scaleMesh... params
@arose do you mean to use this parameters while constructing the geometry? Or in the size theme? 
A question in order to understand.. does scaleFactor is passed to the size theme in some way? I noticed that even if I don't use scaleFactor while constructing the geometry it still works.

**Comment by arose** [comment] 2023-02-15 04:55
Use it while constructing the geometry.

The `scaleFactor` is not passed to the size theme. However for some geometry types (spheres, cylinders, points, lines, text - well all but mesh) it is passed (modified) as uSizeFactor to the vertex shader.

**Comment by giagitom** [comment] 2023-02-15 10:17
Ok thanks, I tried by constructing the geometry. For impostor cylinders I don't have any problem since ```CylinderBuilder.add``` has a ```radiusScale``` parameter. 
Regarding Impostor spheres instead? ```SphereBuilder.add``` has not a radiusScale parameter.. Are there other methods that could be used to construct the spheres geometry?

**Comment by arose** [comment] 2023-02-16 04:18
The spheres geometry does not contain radius data. When you create values for a spheres renderable you include `size` data

https://github.com/molstar/molstar/blob/b2924761abddae9b3c652f76548fa2168ef62cbf/src/mol-geo/geometry/spheres/spheres.ts#L174

https://github.com/molstar/molstar/blob/b2924761abddae9b3c652f76548fa2168ef62cbf/src/mol-geo/geometry/spheres/spheres.ts#L200

and a `sizeFactor`

https://github.com/molstar/molstar/blob/b2924761abddae9b3c652f76548fa2168ef62cbf/src/mol-geo/geometry/spheres/spheres.ts#L211

**Comment by arose** [comment] 2023-02-16 04:19
So for spheres you can change the sizes (like the colors) without touching the geometry.

**Comment by giagitom** [comment] 2023-02-16 16:08
I figured out that seems not possible doing this with the size theme, since I am working on a cartoon representation and the size theme granularity is by residue. Maybe at this point the only way to do this would be by using an additional representation?

**Comment by giagitom** [comment] 2023-02-16 17:31
@arose an other question about meshes.. Is there a particular way to allow normal smoothing on my custom meshes? Should I make something when building meshes in order to allow smooth shading?

**Comment by arose** [comment] 2023-02-17 05:25
> Maybe at this point the only way to do this would be by using an additional representation?

Well anything is possible... When you create a visual you create a geometry with groups and provide a LocationIterator that maps the group to a location. The themes then create a size or color for each location.

Do you want to add another visual to the cartoon representation? Hard to say what would be the best way without knowing more exactly what you want to achieve.

> Is there a particular way to allow normal smoothing on my custom meshes? Should I make something when building meshes in order to allow smooth shading?

There is `Mesh.computeNormals` but you need to call that yourself. There is no automatic normal smoothing and we only use it for external data, for anything else we calculate the normals "analytically".

**Comment by giagitom** [comment] 2023-02-17 17:12
>Well anything is possible... When you create a visual you create a geometry with groups and provide a LocationIterator that maps the group to a location. The themes then create a size or color for each location.

Thanks, good to know this.

>Do you want to add another visual to the cartoon representation? Hard to say what would be the best way without knowing more exactly what you want to achieve.

Yes, I have already made something like this. 
![image](https://user-images.githubusercontent.com/20627977/219717557-f9a515ef-fc2c-40a9-a1c8-a4a20150c9f6.png)

< for anything else we calculate the normals "analytically"
What do you mean here? My final goal would be to smooth non planar rings normals.

**Comment by arose** [comment] 2023-02-18 05:53
I see, nucleotides with sugars. Care to contribute that as a visual for the cartoon repr?

You could add helpers to `MeshBuilder` (could be optimized since the vertices share normals)

```ts
    export function addTriangleWithNormal(state: State, a: Vec3, b: Vec3, c: Vec3, n: Vec3) {
        const { vertices, normals, indices, groups, currentGroup } = state;
        const offset = vertices.elementCount;

        // positions
        caAdd3(vertices, a[0], a[1], a[2]);
        caAdd3(vertices, b[0], b[1], b[2]);
        caAdd3(vertices, c[0], c[1], c[2]);

        for (let i = 0; i < 3; ++i) {
            caAdd3(normals, n[0], n[1], n[2]); // normal
            caAdd(groups, currentGroup); // group
        }
        caAdd3(indices, offset, offset + 1, offset + 2);
    }

    export function addTriangleFanWithNormal(state: State, vertices: ArrayLike<number>, indices: ArrayLike<number>, normal: Vec3) {
        v3fromArray(tmpVecA, vertices, indices[0] * 3);
        for (let i = 2, il = indices.length; i < il; ++i) {
            v3fromArray(tmpVecB, vertices, indices[i - 1] * 3);
            v3fromArray(tmpVecC, vertices, indices[i] * 3);
            addTriangleWithNormal(state, tmpVecA, tmpVecC, tmpVecB, normal);
        }
    }
```

and use them similar to how `addTriangleFan` is used in https://github.com/arose/mesoscale-explorer/blob/mesoscale-explorer/src/mol-repr/structure/visual/nucleotide-ring-mesh.ts#L145 but with a normal vector of your choosing

**Comment by giagitom** [comment] 2023-02-19 01:23
Here it is @arose. Already implemented normal smoothing. It looks very good i think

**Comment by arose** [comment] 2023-04-02 06:21
let's continue any more questions in separate issues or PRs

**Closed by arose** 2023-04-02 06:21 UTC
Labels: question
