### ISSUE TITLE
HETATM rendering problem

### ISSUE THREAD

**Issue by awaterho** [molstar/molstar#229] opened 2021-07-16 14:04 UTC
When loading PDB format files into the https://molstar.org/viewer , we noticed a problem rendering the ligands in this example:

https://swissmodel.expasy.org/templates/5svw.2.pdb

What could be happening there?

I attach a screenshot, and the coordinates here with a .txt extension
[5svw.2.txt](https://github.com/molstar/molstar/files/6831159/5svw.2.txt)

![Clipboard - July 16, 2021 1 56 PM](https://user-images.githubusercontent.com/40768716/125959838-92a0883b-e068-4f4d-bed9-0eaeed603cb2.png)

**Comment by dsehnal** [comment] 2021-07-16 15:14
The HETATM FMN groups are being recognized as nucleotide based on the atom names. For some reason, this does not happen if I only keep the ligands. We will get this fixed, thanks for bringing it up.

@arose any ideas for the cause?

**Comment by arose** [comment] 2021-07-17 18:06
> The HETATM FMN groups are being recognized as nucleotide based on the atom names.

Indeed. Fixed in baa64d81095a6b400fc7d5ad46fe195a22ae2e87 by checking against known mononucleotides.

> For some reason, this does not happen if I only keep the ligands.

It still gets recognized as nucleotide but short polymers are displayed as Ball&Stick not Cartoon.

**Closed by arose** 2021-07-17 18:06 UTC
