### ISSUE TITLE
Focus + Volume Streaming

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#102] opened 2020-11-23 20:37 UTC
Steps to reproduce:
- molstar.org
- load 1cbs
- enable volume streaming
- click on GLU 46

This will focus on the residue, then add the volume visual, then reset the zoom level. Subsequent clicks on this residue will remain zoomed in. Happens commonly when volume data is fetched for the first time, might be more pronounced on slow connections.

**Comment by dsehnal** [comment] 2020-11-23 20:40
Interesting, I get ``WebGL warning: drawArraysInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization.`` with this in the dev build.

**Comment by dsehnal** [comment] 2020-11-23 20:55
Ok, the issue is the automatic camera adjustment when a new object is added that exceeds the existing bounding sphere, which is the case with ``1cbs``.

**Comment by JonStargaryen** [comment] 2020-11-23 21:04
Oh, thanks. I was wondering why this only happens for some structures/residues.

**Comment by dsehnal** [comment] 2020-11-23 21:12
Fixed by https://github.com/molstar/molstar/commit/2987240df43600ae36256139f0e23c46a23aa427, will make new NPM version soon as well.

**Closed** 2020-11-23 22:53 UTC
